server.settings.host=127.0.0.1
server.settings.port=8080
server.settings.reusableAddress=false
server.settings.security.keystore.path=server/security/keys/keystore.jks
server.settings.security.keystore.password=PBmlkEJMm2zUTBMyS+FAGA==
server.settings.security.truststore.path=server/security/keys/truststore.jks
server.settings.security.truststore.password=jWspjHsAOswgvdCswSSu0w==
# available storage type [csv , sql , json]
server.settings.security.authentication.datastore.type=sql
# MYSQL is the only supported DBMS
# NOTE THAT use useSSL= false
server.database.url=jdbc:mysql://127.0.0.1:3306/tcpserver?useSSL=false&allowPublicKeyRetrieval=true
server.database.username=root
server.database.password=xWK087skWpmMkuMwVweS7w==
server.settings.chat.cooldown.second=5
server.hikari.datasource.pool-size=24
server.hikari.datasource.minimum-idle=10
server.hikari.config.cache-prep-stmt=true
server.hikari.config.prep-stmt-cache-size=250
server.hikari.config.prep-stmt-cache-sql-limit=2048
#Recommended connection timeout 10 secondes
server.hikari.config.connection-timeout=10000
server.hikari.config.leak-detection-thres-hold=2000
server.hikari.config.use-server-prep-stmt=true
server.hikari.config.use-local-session-state=true
server.hikari.config.rewrite-batched-statement=true

